import { LandingHeader } from "@/components/landing/landing-header";
import { Footer } from "@/components/footer";

export default function TermsOfServicePage() {
  return (
    <div className="w-full bg-background min-h-screen">
      <LandingHeader />
      
      <main className="max-w-4xl mx-auto px-6 pt-32 pb-24 prose prose-invert prose-slate">
        <h1 className="text-4xl md:text-5xl font-black text-white tracking-tight leading-[1.1] mb-8 uppercase italic">
          Terms of Service
        </h1>
        <p className="text-sm text-text-tertiary">Last Updated: March 2026</p>

        <section className="mt-12 space-y-8 text-text-secondary leading-relaxed">
          <div>
            <h2 className="text-2xl font-bold text-white mt-12 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Aletheia Intelligence ("Aletheia", "we", "our", or "us"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services. Aletheia is designed for professional Open Source Intelligence (OSINT) analysts, security researchers, and lawful investigators.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white mt-12 mb-4">2. Lawful Use Only</h2>
            <p>
              Aletheia provides tools to aggregate, format, and synthesize publicly available information (OSINT) and publicly accessible API endpoints. You agree to use Aletheia strictly for lawful purposes, such as security research, due diligence, and authorized investigations. You explicitly agree not to use Aletheia for:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Harassment, stalking, or doxxing individuals.</li>
              <li>Unauthorized penetration testing or exploiting vulnerabilities.</li>
              <li>Violating the privacy rights or terms of service of any third-party platforms.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white mt-12 mb-4">3. Data Source Accuracy</h2>
            <p>
              Aletheia queries public APIs, web repositories, and licensed data brokers. We do not independently verify the accuracy, completeness, or reliability of the intelligence returned. All data generated in our reports is provided "as is." Probabilistic matching (such as facial recognition or generic username correlation) must be manually verified.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white mt-12 mb-4">4. Subscriptions and Payments</h2>
            <p>
              Payment for premium tiers (Tactical Pro, Elite Team) is processed via authorized Merchants of Record (e.g., Gumroad). Subscriptions are billed on a recurring monthly basis. You may cancel your subscription at any time, but no refunds are provided for partial usage or unused search credits. If an automated payment fails, access to premium features will be suspended until the balance is resolved.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white mt-12 mb-4">5. Account Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account immediately, without notice or refund, if we determine you have violated these Terms of Service or used the platform for malicious compliance violations.
            </p>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white mt-12 mb-4">6. Limitation of Liability</h2>
            <p>
              In no event shall Aletheia Intelligence or its creators be liable for any direct, indirect, incidental, or consequential damages arising from the use or inability to use our services, or resulting from the actionable intelligence generated by the platform.
            </p>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
